/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/a9auUqI2gMB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Analyzer() {
  return (
    (<main
      className="flex flex-col items-center justify-center w-full min-h-screen bg-gray-100 dark:bg-gray-900 p-4 md:p-8">
      <div className="max-w-3xl w-full">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold text-center md:text-4xl dark:text-white">Sustainability Score Generator</h1>
          <p className="text-gray-500 dark:text-gray-400 text-center">
            Enter a URL to get a sustainability score and discover more eco-friendly alternatives.
          </p>
          <div className="flex items-center justify-center space-x-2">
            <Input className="flex-1 max-w-md" dark placeholder="Enter a URL" type="text" />
            <Button dark>Generate Score</Button>
          </div>
        </div>
        <div className="mt-12 space-y-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div
              className="flex flex-col items-center bg-white dark:bg-gray-800 rounded-lg p-6 shadow-lg">
              <div className="text-6xl font-bold text-green-500">85</div>
              <p className="text-gray-500 dark:text-gray-400">Energy Efficiency</p>
            </div>
            <div
              className="flex flex-col items-center bg-white dark:bg-gray-800 rounded-lg p-6 shadow-lg">
              <div className="text-6xl font-bold text-blue-500">92</div>
              <p className="text-gray-500 dark:text-gray-400">Waste Reduction</p>
            </div>
            <div
              className="flex flex-col items-center bg-white dark:bg-gray-800 rounded-lg p-6 shadow-lg">
              <div className="text-6xl font-bold text-yellow-500">78</div>
              <p className="text-gray-500 dark:text-gray-400">Ethical Sourcing</p>
            </div>
          </div>
          <Carousel className="w-full max-w-3xl">
            <CarouselContent>
              <CarouselItem>
                <Card className="bg-white dark:bg-gray-800 shadow-lg">
                  <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
                    <img
                      alt="Alternative 1"
                      className="rounded-full"
                      height={100}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width={100} />
                    <div className="text-center space-y-2">
                      <h3 className="font-bold text-lg dark:text-white">Eco-Friendly Clothing</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Sustainable fashion brand using organic and recycled materials.
                      </p>
                      <Link className="text-green-500 hover:underline dark:text-green-400" href="#">
                        Visit Website
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              </CarouselItem>
              <CarouselItem>
                <Card className="bg-white dark:bg-gray-800 shadow-lg">
                  <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
                    <img
                      alt="Alternative 2"
                      className="rounded-full"
                      height={100}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width={100} />
                    <div className="text-center space-y-2">
                      <h3 className="font-bold text-lg dark:text-white">Sustainable Electronics</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Energy-efficient and ethically-sourced electronics.
                      </p>
                      <Link className="text-green-500 hover:underline dark:text-green-400" href="#">
                        Visit Website
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              </CarouselItem>
              <CarouselItem>
                <Card className="bg-white dark:bg-gray-800 shadow-lg">
                  <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
                    <img
                      alt="Alternative 3"
                      className="rounded-full"
                      height={100}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width={100} />
                    <div className="text-center space-y-2">
                      <h3 className="font-bold text-lg dark:text-white">Eco-Friendly Household</h3>
                      <p className="text-gray-500 dark:text-gray-400">Sustainable home goods and cleaning products.</p>
                      <Link className="text-green-500 hover:underline dark:text-green-400" href="#">
                        Visit Website
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </div>
    </main>)
  );
}
